local helpers = require("spec.helpers")

describe("e911", function()
    it("list", function()
        local c, m = helpers.new_client({ helpers.ok({ records = {} }) })
        c.e911:list()
        assert.are.equal("GET", m.calls[1].method)
        assert.matches("/v2.2/e911$", m.calls[1].url)
    end)

    it("create", function()
        local c, m = helpers.new_client({ helpers.ok({ record = { dn = "12015551234" } }) })
        c.e911:create({ dn = "2015551234", callername = "ACME" })
        assert.are.equal("POST", m.calls[1].method)
    end)

    it("validate", function()
        local c, m = helpers.new_client({ helpers.ok({ address = { addressid = 99 } }) })
        local r = c.e911:validate({ address1 = "1 main", city = "x", state = "NJ", zip = "07030" })
        assert.are.equal(99, r.address.addressid)
        assert.matches("/v2.2/e911/validations$", m.calls[1].url)
    end)

    it("get", function()
        local c, m = helpers.new_client({ helpers.ok({ record = { dn = "12015551234" } }) })
        c.e911:get("2015551234")
        assert.matches("/v2.2/e911/2015551234$", m.calls[1].url)
    end)

    it("provision", function()
        local c, m = helpers.new_client({ helpers.ok({ record = {} }) })
        c.e911:provision("2015551234", { callername = "ACME", addressid = 99 })
        assert.are.equal("PUT", m.calls[1].method)
    end)

    it("remove returns true on 204", function()
        local c = helpers.new_client({ { status = 204, body = "" } })
        local r, err = c.e911:remove("2015551234")
        assert.is_nil(err)
        assert.is_true(r)
    end)

    it("404 error path", function()
        local c = helpers.new_client({ helpers.err(404, "no such dn") })
        local _, err = c.e911:get("9999999999")
        assert.are.equal("not_found", err.kind)
    end)
end)
