local json = require("voicetel.json")

describe("voicetel.json", function()
    it("round-trips a simple object", function()
        local encoded = json.encode({ a = 1, b = "x" })
        local decoded, err = json.decode(encoded)
        assert.is_nil(err)
        assert.are.equal(1, decoded.a)
        assert.are.equal("x", decoded.b)
    end)

    it("encodes empty_array as []", function()
        local got = json.encode({ media = json.empty_array() })
        assert.matches('"media":%[%]', got)
    end)

    it("as_array tags an existing table as a JSON array", function()
        local t = json.as_array({})
        local got = json.encode(t)
        assert.are.equal("[]", got)
    end)

    it("decode returns nil for empty input", function()
        local v, err = json.decode("")
        assert.is_nil(v)
        assert.is_nil(err)
    end)

    it("decode returns an error for invalid JSON", function()
        local v, err = json.decode("{not json")
        assert.is_nil(v)
        assert.is_not_nil(err)
    end)
end)
